### ISSUE TITLE
Unexpected token ∩╗┐

### ISSUE THREAD

**Issue by hawk4031** [rogierschouten/gulp-typedoc#8]
I'm using gulp-typedoc version 1.2.1 and receiving the below error:

    [14:23:14] Using gulpfile ~\Documents\Visual Studio 2013\Projects\FlexViewWeb\FlexViewWeb\gulpfile.js
    [14:23:14] Starting 'typedoc'...
    undefined:1
    ∩╗┐{
    ^
    SyntaxError: Unexpected token ∩╗┐
    at Object.parse (native)
    at PackagePlugin.onBeginResolve (C:\[truncated]\node_modules\gulp-typedoc\node_modules\typedoc\bin\typedoc.js:5334:48)
    at Converter.EventDispatcher.dispatch (C:\[truncated]\node_modules\gulp-typedoc\node_modules\typedoc\bin\typedoc.js:102:34)
    at Converter.resolve (C:\[truncated]\node_modules\gulp-typedoc\node_modules\typedoc\bin\typedoc.js:2048:22)
    at Converter.convert (C:\[truncated]\node_modules\gulp-typedoc\node_modules\typedoc\bin\typedoc.js:2005:36)
    at Application.convert (C:\[truncated]\node_modules\gulp-typedoc\node_modules\typedoc\bin\typedoc.js:430:41)
    at Stream.<anonymous> (C:\[truncated]\node_modules\gulp-typedoc\index.js:54:22)
    at _end (C:\[truncated]b\node_modules\gulp-typedoc\node_modules\event-stream\node_modules\through\index.js:65:9)
    at Stream.stream.end (C:\[truncated]\node_modules\gulp-typedoc\node_modules\event-stream\node_modules\through\index.js:74:5)
    at DestroyableTransform.onend (C:\[truncated]\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:523:10
    )

My gulp task looks like:

    gulp.task("typedoc", function () {
    return gulp
        .src(["Engineering/App/**/*.ts"])
        .pipe(typedoc({
            module: "commonjs",
            target: "es5",
            out: "docs/",
            name: "FlexView Web"
        }))
    ;
});

To my knowledge, there aren't any strange characters in my Typescript files. Ideas?

**Comment by rogierschouten** [comment]
I think you need to report this to TypeDoc instead of gulp-typedoc?

**Comment by hawk4031** [comment]
Ah yes. I see when I run just typedoc that I get the same error. I will post over there. Thanks!
